### ISSUE TITLE
FYI: TV Shows (and others) fail with KeyError Exception

### ISSUE THREAD

**Issue by koucos** [Twilight0/plugin.video.ert.gr#12]
Hi ... 
My setup is RaspberryPi (2B and 3B+) running LibreELEC (official): 9.2.8 (RPi2.arm)
Ertflix add-on updates automatically.
The problem arises with every 4.0.x update.
Accessing TVShows for instance fails with the following message in the log file:

--- cut here ---
2021-12-23 21:00:40.128 T:1482679168   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'totalPages'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/router.py", line 35, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/router.py", line 29, in main
                                                urldispatcher.dispatch(action, params)
                                              File "/storage/.kodi/addons/script.module.tulip/lib/tulip/url_dispatcher.py", line 95, in dispatch
                                                self.func_registry[action](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/navigator.py", line 640, in categories
                                                self_list = category_list(url)
                                              File "/storage/.kodi/addons/script.module.tulip/lib/tulip/cache.py", line 368, in memoizer
                                                payload = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/navigator.py", line 609, in category_list
                                                total_pages = pages[codename]['totalPages']
                                            KeyError: 'totalPages'
                                            -->End of Python script error report<--
--- cut here ---

Quick and dirty solution:
Replace line 609 in navigator.py with "total_pages = pages[codename]['totalPages'] if 'totalPages' in pages[codename] else 1"
and everything seems to run correctly ... or i believe so ...
Since i do not have the total grasp of the code, you could possibly find a much better solution.
Please accept my gratitude and respect for your excellent work on this add-on. Keep up the good work

**Comment by Twilight0** [comment]
Its dirty indeed, I 'll deploy a workaround soon, they were working just a couple of hours ago.

**Comment by ghost** [comment]
Hi,

I have changed line 393 to "script = client.parseDOM(html, 'script')[1]" and line 603 to "script = client.parseDOM(html, 'script')[1].partition('</script>')[0].replace('var ___INITIAL_STATE__ = ', '')[:-1]" in navigator.py and seems to be ok.

**Comment by MacGyver00** [comment]
> Hi,
> 
> I have changed line 393 to "script = client.parseDOM(html, 'script')[1]" and line 603 to "script = client.parseDOM(html, 'script')[1].partition('</script>')[0].replace('var _**INITIAL_STATE** = ', '')[:-1]" in navigator.py and seems to be ok.

You made my day!
Also, many thanks to Twilight0 for this excellent plugin!

**Comment by Twilight0** [comment]
You could've submit  PR for this. I am applying it now. Please close the issue if this resolves it on your setup.

**Comment by MacGyver00** [comment]
Strangely, for me the problem started suddenly yesterday (raspberry pi4). Until then the plugin worked without problem. Looking for a solution I found gthal's solution above. Is this due to a change in ertflix.gr?

**Comment by Twilight0** [comment]
Fixed in 4.0.7, issue closed.

**Comment by koucos** [comment]
Hello again ...
Strange though it may seem ... the same problem persists ...!!!
Latest version 4.0.8 (and not 4.0.7 as you mentioned in your reply ...), uninstalled and installed again from your repository Twilight0 - 1.4.
Function cache successfully cleared. 
TV-Shows and TV-Series fail with the following message ... Movies is OK ...
------------------- cut here for error message ----------------
...
2022-01-15 18:57:19.516 T:1937515584 WARNING: CGUIWindowManager - HandleAction - ignoring action 107, because topmost modal dialog closing animation is running
2022-01-15 18:57:24.731 T:1455408000 WARNING: Previous line repeats 2 times.
2022-01-15 18:57:24.736 T:1455408000   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'totalPages'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/router.py", line 35, in <module>
                                                sys.exit(main())
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/router.py", line 29, in main
                                                urldispatcher.dispatch(action, params)
                                              File "/storage/.kodi/addons/script.module.tulip/lib/tulip/url_dispatcher.py", line 95, in dispatch
                                                self.func_registry[action](*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/navigator.py", line 648, in categories
                                                self_list = category_list(url)
                                              File "/storage/.kodi/addons/script.module.tulip/lib/tulip/cache.py", line 368, in memoizer
                                                payload = func(*args, **kwargs)
                                              File "/storage/.kodi/addons/plugin.video.ert.gr/resources/lib/navigator.py", line 617, in category_list
                                                total_pages = pages[codename]['totalPages']
                                            KeyError: 'totalPages'
                                            -->End of Python script error report<--
2022-01-15 18:57:24.979 T:1480586112   ERROR: GetDirectory - Error getting plugin://plugin.video.ert.gr/?action=categories&title=TV%20Shows&url=https%3a%2f%2fwww.ertflix.gr%2fshow%2fekpompes
2022-01-15 18:57:24.981 T:1937515584   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.ert.gr/?action=categories&title=TV%20Shows&url=https%3a%2f%2fwww.ertflix.gr%2fshow%2fekpompes) failed
...
------------------ cut here for error message -----------------

any ideas ????
Let me know if you need any further info.
Thanks again for your effort.

**Comment by Twilight0** [comment]
Can't reproduce, all sections work ok for me.
